### ISSUE TITLE
[0.2] Progress Tracking Issue

### ISSUE THREAD

**Issue by emerali** [PIQuIL/QuCumber#32]
Todo List for 0.2:

# Important
- [x]  Merge in Observables update to `develop`
- [x]  Merge LivePlotting into `develop`
- [x]  Polish up tutorials
- [x]  Make sure docs are up to date and building properly
- [x]  Merge `playground` into `develop`
- [ ]  Test fresh install on Linux + Windows
- [ ]  Make sure code is passing `flake8` tests
- [x]  Make sure everything works with torch 0.4.1

**Comment by GTorlai** [comment]
- [ ] Change name tutorial 2
