### ISSUE TITLE
[0.3] Release Tracking Issue

### ISSUE THREAD

**Issue by emerali** [PIQuIL/QuCumber#37]
Important
- [x] Unit testing (#16)
- [x] Flake8/black & Radon style/complexity checking
- [x] ComplexRBM gradient rotation optimizations (#38, and #50)
- [x] AbstractWavefunction class (related: #42)
- [x] ~More efficient sampling for Wavefunctions (like with Observables) (maybe?)~
    - nah, would need to provide `burn_in`, `steps` parameters; probably too much for the end-user
- [x] Appveyor (#4)
- [x] ReadTheDocs (related: #40)
- [x] Check it memory leak still exists (#39)
- [x] README
    - [x] how to install
    - [x] setup development env
- [x] requirements*.txt
- [x] Clean-up tutorials
